services:
  - type: web
    name: amazonfindins
    env: java
    buildCommand: mvn clean package
    startCommand: java -jar target/affiliate-marketing-app-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_ADMIN_USERNAME
        sync: false
      - key: APP_ADMIN_PASSWORD
        sync: false
      - key: APP_ADMIN_TOKEN
        sync: false
